name: Trigger auto deployment for django-test-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/django-test-2-AutoDeployTrigger-2ed51489-985c-4b97-b029-ccf7a9daca0a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DJANGOTEST2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DJANGOTEST2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DJANGOTEST2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry3viwetoqeu7r6.azurecr.io
          registryUsername: ${{ secrets.DJANGOTEST2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DJANGOTEST2_REGISTRY_PASSWORD }}
          containerAppName: django-test-2
          resourceGroup: airwavesapi938a
          imageToBuild: containerregistry3viwetoqeu7r6.azurecr.io/django-test-2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


